import * as moment from "moment";

export let config: any = {
    productionMode: false,
//     adminMode: true,
//     adminIcon: "buhta/assets/icons/admin.png",
//     theme: "buhta",
//     border: "1px solid #d4d4d4",
//     borderColor: "#d4d4d4",
//     mainDatabaseName: "main",
//     font: {
//         family: "Ubuntu",
//         style: "normal",
//         size: 13
//
//     },
//     comboBox: {
//         itemHeight: 20,
//     },
//     formPanel: {
//         inputVerticalSpace: 5,
//
//         errorMessageColor: "tomato",
//         errorMessageFontSize: 12,
//         errorMessageFontStyle: "italic",
//         errorInputBackground: "rgb(255, 241, 239)",
//         errorMessageMaxLength: 50,
//
//         inputDefaultColor: "black",
//         inputChangedColor: "#108ee9",
//         //inputChangedBackground: "#eaf6ffc7",
//
//         labelColor: "cadetblue",
//     },
//     button: {
//         okIcon: "vendor/fugue/tick.png",
//         saveIcon: "vendor/fugue/disk.png",
//         applyIcon: "vendor/fugue/disks-black.png",
//         cancelIcon: "vendor/fugue/cross-script.png",
//         insertRowIcon: "vendor/fugue/plus.png",
//         changeRowIcon: "vendor/fugue/card--pencil.png",
//         deleteRowIcon: "vendor/fugue/cross.png",
//         focusedBorder: "1px solid dodgerblue",
//         refreshIcon: "buhta/assets/icons/refresh.png",
//         runIcon: "buhta/assets/icons/run.png",
//         undoIcon: "vendor/fugue/arrow-curve-180.png",
//         redoIcon: "vendor/fugue/arrow-curve.png",
//     },
//     baseInput: {
//         height: 24,
//         width: 300,
//     },
//     numberInput: {
//         decimalSeparator: ".",
//         digits: 12,
//         groupSeparator: " ",
//         width: 150,
//         negativeColor: "red"
//     },
//     sql: {
//         maxIdentifierLength: 127,
//         maxStringLength: 4096,
//         maxColumnsInTable: 4096,
//         maxMoneyValue: 69999999999999.99,
//         minMoneyValue: -69999999999999.99,
//         maxDecimal: {
//             "9,1": 99999999.9,
//             "9,2": 9999999.99,
//             "9,3": 999999.999,
//             "9,4": 99999.9999,
//             "9,5": 9999.99999,
//             "9,6": 999.999999,
//             "9,7": 99.9999999,
//             "16,1": 699999999999999.9,
//             "16,2": 69999999999999.99,
//             "16,3": 6999999999999.999,
//             "16,4": 699999999999.9999,
//             "16,5": 69999999999.99999,
//             "16,6": 6999999999.999999,
//             "16,7": 699999999.9999999,
//             "16,8": 69999999.99999999,
//             "16,9": 6999999.999999999,
//             "16,10": 699999.9999999999,
//             "16,11": 69999.99999999999,
//             "16,12": 6999.999999999999,
//             "16,13": 699.9999999999999,
//             "16,14": 69.99999999999999,
//         },
//         minDate: moment("0001-01-02"),
//         maxDate: moment("9999-12-31"),
//         minDateTime: moment("0001-01-02 00:00:00.001"),
//         maxDateTime: moment("9999-12-31 23:59:59.999"),
//
//         fkDataTypeColor: "darkcyan",
//         blobDataTypeColor: "olive",
//         booleanDataTypeColor: "tomato",
//         dateDataTypeColor: "royalblue",
//         dateTimeDataTypeColor: "royalblue",
//         decimalDataTypeColor: "black",
//         integerDataTypeColor: "black",
//         moneyDataTypeColor: "forestgreen",
//         guidDataTypeColor: "darkorange",
//         stringDataTypeColor: "brown",
//
//     },
//     grid: {
//         rowsHeight: 21
//     },
//     dbGrid: {
//         //rowsHeight: 21
//         toolbar: {
//             reloadIcon: "buhta/assets/icons/refresh.png",
// //            findIcon: "vendor/fugue/binocular.png",
//             findIcon: "vendor/fugue/magnifier.png",
//             findNextIcon: "buhta/assets/icons/magnifier--arrow-down.png",
//             findPrevIcon: "buhta/assets/icons/magnifier--arrow-up.png",
//             filterIcon: "vendor/fugue/funnel.png",
//             filterPlusIcon: "vendor/fugue/funnel--plus.png",
//             filterMinusIcon: "vendor/fugue/funnel--minus.png",
//             filterInputIcon: "buhta/assets/icons/funnel--input.png",
//             filterResetIcon: "buhta/assets/icons/funnel--reset.png",
//
//             checkboxesIcon: "buhta/assets/icons/grid-checkboxes.png",
//             checkboxesAllIcon: "buhta/assets/icons/grid-checkboxes-all.png",
//             checkboxesNoneIcon: "buhta/assets/icons/grid-checkboxes-none.png",
//
//             sortAscIcon: "buhta/assets/icons/sort-asc.png",
//             sortDescIcon: "buhta/assets/icons/sort-desc.png",
//             sortResetIcon: "buhta/assets/icons/sort-reset.png",
//         }
//     },
//     CSS_COLOR_NAMES: [
//         "AliceBlue", "AntiqueWhite", "Aqua", "Aquamarine", "Azure", "Beige", "Bisque", "Black", "BlanchedAlmond",
//         "Blue", "BlueViolet", "Brown", "BurlyWood", "CadetBlue", "Chartreuse", "Chocolate", "Coral",
//         "CornflowerBlue", "Cornsilk", "Crimson", "Cyan", "DarkBlue", "DarkCyan", "DarkGoldenRod", "DarkGray",
//         "DarkGrey", "DarkGreen", "DarkKhaki", "DarkMagenta", "DarkOliveGreen", "Darkorange", "DarkOrchid",
//         "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue", "DarkSlateGray", "DarkSlateGrey",
//         "DarkTurquoise", "DarkViolet", "DeepPink", "DeepSkyBlue", "DimGray", "DimGrey", "DodgerBlue", "FireBrick",
//         "FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite", "Gold", "GoldenRod", "Gray", "Grey",
//         "Green", "GreenYellow", "HoneyDew", "HotPink", "IndianRed", "Indigo", "Ivory", "Khaki", "Lavender",
//         "LavenderBlush", "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral", "LightCyan", "LightGoldenRodYellow",
//         "LightGray", "LightGrey", "LightGreen", "LightPink", "LightSalmon", "LightSeaGreen", "LightSkyBlue",
//         "LightSlateGray", "LightSlateGrey", "LightSteelBlue", "LightYellow", "Lime", "LimeGreen", "Linen",
//         "Magenta", "Maroon", "MediumAquaMarine", "MediumBlue", "MediumOrchid", "MediumPurple", "MediumSeaGreen",
//         "MediumSlateBlue", "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "MidnightBlue", "MintCream",
//         "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace", "Olive", "OliveDrab", "Orange", "OrangeRed",
//         "Orchid", "PaleGoldenRod", "PaleGreen", "PaleTurquoise", "PaleVioletRed", "PapayaWhip", "PeachPuff",
//         "Peru", "Pink", "Plum", "PowderBlue", "Purple", "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon",
//         "SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver", "SkyBlue", "SlateBlue", "SlateGray", "SlateGrey",
//         "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato", "Turquoise", "Violet", "Wheat",
//         "White", "WhiteSmoke", "Yellow", "YellowGreen"],
//
//     htmlColorGroups: [
//         {
//             groupName: "RED HTML COLORS",
//             colors: [
//                 "indianred",
//                 "lightcoral",
//                 "salmon",
//                 "darksalmon",
//                 "lightsalmon",
//                 "crimson",
//                 "red",
//                 "firebrick",
//                 "darkred",
//             ]
//         },
//         {
//             groupName: "PINK HTML COLORS",
//             colors: [
//                 "pink",
//                 "lightpink",
//                 "hotpink",
//                 "deeppink",
//                 "mediumvioletred",
//                 "palevioletred",
//             ]
//         },
//         {
//             groupName: "ORANGE HTML COLORS",
//             colors: [
//                 "lightsalmon",
//                 "coral",
//                 "tomato",
//                 "orangered",
//                 "darkorange",
//                 "orange",
//             ]
//         },
//         {
//             groupName: "YELLOW HTML COLORS",
//             colors: [
//                 "gold",
//                 "yellow",
//                 "lightyellow",
//                 "lemonchiffon",
//                 "lightgoldenrodyellow",
//                 "papayawhip",
//                 "moccasin",
//                 "peachpuff",
//                 "palegoldenrod",
//                 "khaki",
//                 "darkkhaki",
//             ]
//         },
//         {
//             groupName: "PURPLE HTML COLORS",
//             colors: [
//                 "lavender",
//                 "thistle",
//                 "plum",
//                 "violet",
//                 "orchid",
//                 "fuchsia",
//                 "magenta",
//                 "mediumorchid",
//                 "mediumpurple",
//                 "rebeccapurple",
//                 "blueviolet",
//                 "darkviolet",
//                 "darkorchid",
//                 "darkmagenta",
//                 "purple",
//                 "indigo",
//                 "slateblue",
//                 "darkslateblue",
//                 "mediumslateblue",
//             ]
//         },
//         {
//             groupName: "GREEN HTML COLORS",
//             colors: [
//                 "greenyellow",
//                 "chartreuse",
//                 "lawngreen",
//                 "lime",
//                 "limegreen",
//                 "palegreen",
//                 "lightgreen",
//                 "mediumspringgreen",
//                 "springgreen",
//                 "mediumseagreen",
//                 "seagreen",
//                 "forestgreen",
//                 "green",
//                 "darkgreen",
//                 "yellowgreen",
//                 "olivedrab",
//                 "olive",
//                 "darkolivegreen",
//                 "mediumaquamarine",
//                 "darkseagreen",
//                 "lightseagreen",
//                 "darkcyan",
//                 "teal",
//             ]
//         },
//         {
//             groupName: "BLUE HTML COLORS",
//             colors: [
//                 "aqua",
//                 "cyan",
//                 "lightcyan",
//                 "paleturquoise",
//                 "aquamarine",
//                 "turquoise",
//                 "mediumturquoise",
//                 "darkturquoise",
//                 "cadetblue",
//                 "steelblue",
//                 "lightsteelblue",
//                 "powderblue",
//                 "lightblue",
//                 "skyblue",
//                 "lightskyblue",
//                 "deepskyblue",
//                 "dodgerblue",
//                 "cornflowerblue",
//                 "mediumslateblue",
//                 "royalblue",
//                 "blue",
//                 "mediumblue",
//                 "darkblue",
//                 "navy",
//                 "midnightblue",
//             ]
//         },
//         {
//             groupName: "BROWN HTML COLORS",
//             colors: [
//                 "cornsilk",
//                 "blanchedalmond",
//                 "bisque",
//                 "navajowhite",
//                 "wheat",
//                 "burlywood",
//                 "tan",
//                 "rosybrown",
//                 "sandybrown",
//                 "goldenrod",
//                 "darkgoldenrod",
//                 "peru",
//                 "chocolate",
//                 "saddlebrown",
//                 "sienna",
//                 "brown",
//                 "maroon",
//             ]
//         },
//         {
//             groupName: "WHITE HTML COLORS",
//             colors: [
//                 "white",
//                 "snow",
//                 "honeydew",
//                 "mintcream",
//                 "aliceblue",
//                 "ghostwhite",
//                 "whitesmoke",
//                 "seashell",
//                 "beige",
//                 "oldlace",
//                 "floralwhite",
//                 "ivory",
//                 "antiquewhite",
//                 "linen",
//                 "lavenderblush",
//                 "mistyrose",
//             ]
//         },
//         {
//             groupName: "GRAY HTML COLORS",
//             colors: [
//                 "gainsboro",
//                 "lightgray",
//                 "silver",
//                 "darkgray",
//                 "gray",
//                 "dimgray",
//                 "lightslategray",
//                 "slategray",
//                 "darkslategray",
//                 "black",
//             ]
//         },
//     ]
};